
version: 2

models:
  - name: raw_deals_flattened
    description: "Intermediate step to get deals properties"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: archived
        description: "Boolean that indicates if the deal is archived"
      - name: createdAt
        description: "Creation timestamp"
      - name: updatedAt
        description: "Last update timestamp"
      - name: properties
        description: "JSON object with deals properties"
      - name: deals
        description: "Column with the list of deals associated to a note"
