
#Project name and general info
name: 'deals_transformations'
version: '1.0.0'
config-version: 2

profile: 'deals_transformations'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Specify where to install packages
packages-install-path: "../dbt_packages"

# directory which will store compiled SQL files
target-path: "target"

# directory which will store logs
log-path: ../logs

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "../dbt_packages"

# Models settings
models:
  deals_transformations:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    deals_matcher:
      +materialized: table
